### ISSUE TITLE
Archive course 2018

### ISSUE THREAD

**Issue by AMashoshyna** [kottans/frontend#99]
Move materials related to past course to archive directory

**Comment by OleksiyRudenko** [comment]
There is a tag `v.2017-2018` that also denotes a [release](https://github.com/kottans/frontend/releases), i.e. state of the repo as of last course end.
The idea behind was to enable checkout by tag whenever you need to refer to the content in the past. Just like with any product.
Won't this do?
P.S. Hopefully, new course will add or update materials rather than remove any.

**Comment by AMashoshyna** [comment]
Got it, thanks! PR was updated. I have removed documents which are no longer relevant or need significant update (schedule, students list, program drafts, setup instructions for organization). Newcomers may be confused to see those.

**Comment by AMashoshyna** [comment]
Closed with PR #100
